roth-michael/FoundryVTT-RestRecovery

languages/fr.json
module.json

Feat lang FR

---

languages/de.json
module.json

@Haxxer Thanks for this amazing module! This adds a german translation. :)

Add german translation

---

scripts/rest-workflow.js

This PR was left as a convenience solution for regarding bug #181. Do not accept pull unless you think this will work. At the very least a change is necessary since the current syntax cannot work .
I can do more later once I figure out how to setup a proper testing environment.

Untested Commit, Moved hitDiceRecovered to be at the last line it is in scope

---

changelog.md
module.json
scripts/rest-workflow.js

fix spell slot removal during custom recovery

---

README.md
changelog.md
languages/en.json
module.json
scripts/constants.js
scripts/formapplications/prompt-rest/prompt-rest-shell.svelte
scripts/formapplications/quick-setup/quick-setup-shell.svelte
scripts/lib/lib.js
scripts/rest-workflow.js

Should close #183 and close #189

custom rest lengths

---

changelog.md
languages/en.json
languages/pt_BR.json
module.json
scripts/formapplications/prompt-rest/prompt-rest-shell.svelte
scripts/hooks.js
scripts/sheet-overrides.js

sheet fixes & translation updates

---

changelog.md
module.json
scripts/rest-workflow.js

added ddbi rations to automatic recognition

---

changelog.md
module.json
scripts/constants.js
scripts/settings.js
scripts/sheet-overrides.js

fix food/water bugs

---

languages/en.json
scripts/constants.js
scripts/rest-workflow.js

WIP. Still testing.
Allows users to modify how hit dice are rolled. either normal, with advantage (take the highest of 2 rolls) or maximize the roll.

hit dice roll formula

---

changelog.md
languages/en.json
languages/pt_BR.json
module.json
scripts/constants.js
scripts/migrations.js
scripts/rest-workflow.js

closes #231, should implement #168

fixed up roll formula config, moved multiplier to general

---

changelog.md
module.json
scripts/constants.js
scripts/formapplications/prompt-rest/prompt-rest-shell.svelte
scripts/migrations.js

rest config data now saved on user document

---

changelog.md
module.json
scripts/formapplications/long-rest/long-rest-shell.svelte
scripts/formapplications/short-rest/short-rest-shell.svelte
scripts/rest-workflow.js

fix npc resting

---

changelog.md
module.json
scripts/formapplications/prompt-rest/prompt-rest-shell.svelte

filter priorityActors to not include null/undefined

---

changelog.md
languages/en.json
module.json
scripts/constants.js
scripts/rest-workflow.js

homebrew song of rest functionality

---

changelog.md
module.json
scripts/formapplications/long-rest/long-rest-shell.svelte
scripts/module.js

fix long hd, tidy settings

---

changelog.md
module.json
scripts/lib/lib.js
scripts/rest-workflow.js

fixed dynamic max uses

---

changelog.md
scripts/module.js

fix exhaustion reference

---

changelog.md
module.json
scripts/rest-workflow.js

- Fixed an error when consuming food/water which has only a quantity, rather than limited uses

quantity consumption fix

---

changelog.md
languages/en.json
scripts/constants.js
scripts/rest-workflow.js

Natural Recovery fix

---

changelog.md
scripts/rest-workflow.js

HD buffer fix, activity-getting cleanup

---

changelog.md
scripts/rest-workflow.js

Consume 1 charge by default

---

changelog.md
scripts/rest-workflow.js

Consider `tempmax` during hp regain
